BEGIN;

-- Dropping the tables
DROP TABLE IF EXISTS Payments;
DROP TABLE IF EXISTS Shipping;
DROP TABLE IF EXISTS Order_Items;
DROP TABLE IF EXISTS Cart_Items;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Cart;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Categories;

COMMIT;
